[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/astropay/go-tools"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/pressly/goose"
  version = "v2.7.0-rc4"